version: '3.8'
services:
    db:
        image: postgres:13
        user: root
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - POSTGRES_DB=postgres
        ports:
            - 5432:5432
    odoo:
        image: odoo-x86
        user: odoo
        tty: true
        depends_on:
            - db
        environment:
            - PYTHONUNBUFFERED=1
        ports:
            - 8069:8069
            - 5678:5678
        volumes:
            # пробрасываем внутрь контейнера сам каталог с odoo
            - $ODOO_PATH:$DOCKER_ODOO_DIR
            # пробрасываем конфигурационный файл вашего проекта внутрь контейнера
            - $PROJECT_DIR_PATH/dev_odoo_docker_config_file.conf:$DOCKER_PROJECT_DIR/odoo.conf
            # поскольку контейнер у нас по сути одноразовый мы здесь пробросим каталог со статическими ресурсами к себе в проект
            - $DOCKER_HOME/.local :$DOCKER_PROJECT_DIR/.local
            # пробрасываем каталог, который содержит виртуальное окружения для нашего проекта
            - $PROJECT_DIR_PATH/venv:$DOCKER_VENV_DIR
            #  пробрасываем файл дополнительными python пакетами, которые мы используем в своем проекте
            - $PROJECT_DIR_PATH/requirements.txt:$DOCKER_PROJECT_DIR/requirements.txt
            # Пробрасываем каталог с кешем прекоммита, если что, мы всегда можем его удалить и он установиться заново
            - $DOCKER_HOME/.cache:$DOCKER_PROJECT_DIR/.cache
            # пробрасываем непосредственно сам проект с разрабатываемыми модуляим
            - $OODOO_PROJECT_DIR_PATH:$DOCKER_ODOO_PROJECT_DIR_PATH
            

            # Берем файлы из разрабатываемого проекта оду $OODOO_PROJECT_DIR_PATH, копируем к себе в 
            # каталог с нашим проектом $PROJECT_DIR_PATH и пробасываем файлы для pre-commit т.к. нам необходимо вносить в них ряд изменений.
            # Это не обязательные параметры, но, т.к. использование пре-коммита может быть продиктовано
            # самим проектом odoo в котором вы работаете, то вы будете обязаны его использовать, поэтому
            # я привел пример как использовать пре-коммит внутри докер контейнера с настройками из проекта
            #  при этом вы можете вносить точечные изменения, как в нашем случае - игнорирование всех ошибок связанных
            # с тем, что все файлы внутри контейнера видны как исполняемые.
            - $PROJECT_DIR_PATH/.flake8:$DOCKER_ODOO_PROJECT_DIR_PATH/.flake8
            - $PROJECT_DIR_PATH/.pylintrc:$DOCKER_ODOO_PROJECT_DIR_PATH/.pylintrc
            - $PROJECT_DIR_PATH/.pylintrc-mandatory:$DOCKER_ODOO_PROJECT_DIR_PATH/.pylintrc-mandatory

        command: $START_STRING